/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.*;
import javax.swing.*;
/**
 *
 * @author ka907986
 */
public class VisuJoueursDlg extends javax.swing.JDialog {

    /**
     * Creates new form VisuJoueursDlg
     */
    // Attributs 
    private LesJoueurs lj; 
    
    
    public VisuJoueursDlg(java.awt.Frame parent, boolean modal,LesJoueurs lesj) {
        super(parent, modal);
        initComponents();
        
         // Initialisation de l'attribut avec le parametre
        this.lj = lesj;
        //appeldela creation des boutons 
        initTrombi();
        
        
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // methode
    private void afficheTrombi()
    {
        for(int i=0 ; i<this.lj.getNbJoueurs();i++)
        {
            // on recupere le ieme bouton 
            BoutonImage jb =(BoutonImage)Panneau.getComponent(i);
            Joueur j= this.lj.getJoueur(i); //on recupere le joueur d'indice i
            //jb.setIcon(j.getPhoto());
            Image img = j.getPhoto().getImage().getScaledInstance(jb.getWidth(),jb.getHeight(),Image.SCALE_SMOOTH);
            jb.setIcon(new ImageIcon(img));
            
            jb.paint(jb.getGraphics());
        }
    }
    
    
    //Methode pour creer  les boutons pour les images
    private void initTrombi()
    { 
        int nb = this.lj.getNbJoueurs();
        Panneau.setLayout(new GridLayout(1,nb));
        for (int i=0; i< nb; i++)
        {
            BoutonImage jb= new BoutonImage();
            Joueur j= lj.getJoueur(i);
            jb.setName(""+i);
            jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            AfficheInfosJoueur(evt);
            }
            });
            Panneau.add(jb);
        }
        this.pack(); // pour ajuster correctement la taille des composants après les ajouts si besoin
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTitre = new javax.swing.JLabel();
        BBas = new javax.swing.JPanel();
        Afficher = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Panneau = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LTitre.setText("Choisissez un joueur pour voir ses caractéristiques");
        getContentPane().add(LTitre, java.awt.BorderLayout.NORTH);

        BBas.setLayout(new java.awt.GridLayout(1, 1));

        Afficher.setText("Afficher");
        Afficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AfficherActionPerformed(evt);
            }
        });
        BBas.add(Afficher);

        getContentPane().add(BBas, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout PanneauLayout = new javax.swing.GroupLayout(Panneau);
        Panneau.setLayout(PanneauLayout);
        PanneauLayout.setHorizontalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
        PanneauLayout.setVerticalGroup(
            PanneauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel3.add(Panneau, java.awt.BorderLayout.CENTER);

        Edition.setEditable(false);
        Edition.setColumns(20);
        Edition.setLineWrap(true);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // methode lie au bouton afficher
    private void AfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AfficherActionPerformed
        // TODO add your handling code here:
        afficheTrombi();
    }//GEN-LAST:event_AfficherActionPerformed

    // methode qui affiche les imformations des joueurs dans la zone d'edition
    private void AfficheInfosJoueur(java.awt.event.ActionEvent evt) { 
    
       for (int i=0 ; i<this.lj.getNbJoueurs(); i++)
       {   BoutonImage jb = (BoutonImage) Panneau.getComponent(i);
           
           if(evt.getSource().equals(jb))
           {
              Edition.setText(this.lj.getJoueur(i).toString());
           }
       }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueursDlg dialog = new VisuJoueursDlg(new javax.swing.JFrame(), true, new LesJoueurs());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afficher;
    private javax.swing.JPanel BBas;
    private javax.swing.JTextArea Edition;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel Panneau;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
